site_name: CS231n Notes
theme:
  name: material
  language: en
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  primary: light blue
  features:
    - navigation.top
repo_url: https://github.com/kantarcise/cs231n
nav:
  - Home: index.md
  - Assignments: assignments/README.md
  - Lectures:
    - "1. Intro to Computer Vision": lectures/lecture01.md
    - "2. Image classification and Data-driven approach": lectures/lecture02.md
    - "3. Linear classification, Optimization, SGD": lectures/lecture03.md
    - "4. Backpropagation & Intro to Neural Networks": lectures/lecture04.md
    - "5. Training Neural Networks Part 1": lectures/lecture05.md
    - "6. Training Neural Networks Part 2": lectures/lecture06.md
    - "7. Convolutional Neural Networks": lectures/lecture07.md
    - "8. ConvNets for spatial localization, Object Detection": lectures/lecture08.md
    - "9. Understanding and visualizing ConvNets": lectures/lecture09.md
    - "10. Recurrent Neural Networks (RNN), Long Short Term Memory (LSTM)": lectures/lecture10.md
    - "11. Training ConvNets in practice, Distributed training": lectures/lecture11.md
    - "12. Overview of Caffe/Torch/Theano/TensorFlow": lectures/lecture12.md
    - "13. Segmentation": lectures/lecture13.md
    - "14. ConvNets for videos": lectures/lecture14.md
    - "15. Closing and Guest Lecture": lectures/lecture15.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.tasklist:
      custom_checkbox: true
